name: CI
on: push

jobs:
  CI:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [macos-11, macOS-12]

    steps:
    - name: ${{github.workflow}}
      uses: danielbayley/homebrew-pipeline@main
      env:
        ACTIONS_STEP_DEBUG: ${{secrets.ACTIONS_STEP_DEBUG}}
